[package]
name = "avalanche-rs"
authors = ["Aur√©lien Foucault"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
lazy_static = "1.4.0"
